services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    restart: always
    ports:
      - "8085:8085"
      - "50000:50000"
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /root/Docker_Sql:/root/Docker_Sql
      - /root/Backup:/root/Backup
    environment:
      JENKINS_OPTS: --httpPort=8085

volumes:
  jenkins_home:
